#!/bin/bash

function downloadSpigot {
  local match
  case "$TYPE" in
    *BUKKIT|*bukkit)
      match="craftbukkit"
      tail="-SNAPSHOT.jar"
      downloadUrl=${BUKKIT_DOWNLOAD_URL}
      ;;
    *)
      match="spigot"
      tail=".jar"
      downloadUrl=${SPIGOT_DOWNLOAD_URL}
      ;;
  esac

  norm=$VANILLA_VERSION
  case $VANILLA_VERSION in
    *.*.*)
      norm=$VANILLA_VERSION ;;
    *.*)
      norm=${VANILLA_VERSION}.0 ;;
  esac

  url="https://cdn.getbukkit.org/"
  if [[ -z $downloadUrl ]]; then
    downloadUrl="$url$match/$match-$norm$tail"
    if [[ -z $downloadUrl ]]; then
      echo "ERROR: Version $VANILLA_VERSION is not supported for $TYPE"
      echo "Url: $downloadUrl"
      exit 2
    fi
  fi

  echo "Downloading $match"
  curl -kfsSL -o $SERVER "$downloadUrl"
  status=$?
  if [ ! -f $SERVER ]; then
    echo "ERROR: failed to download from $downloadUrl (status=$status)"
    exit 3
  fi

}

case "$TYPE" in
  *BUKKIT|*bukkit)
    export SERVER=craftbukkit_server.jar
    ;;
  *)
    export SERVER=spigot_server.jar
    ;;
esac

if [ ! -f $SERVER ]; then
  downloadSpigot
fi

# Normalize on Spigot for operations below
export TYPE=SPIGOT

# Continue to Final Setup
exec start-finalSetup01World $@
