#!/bin/bash

export SERVER=paper_server.jar
if [ ! -f $SERVER ]; then
  local build
  case "$VERSION" in
    latest|LATEST|1.12.2)
      build="lastSuccessfulBuild";;
    1.11.2)
      build="1104";;
    1.10.2)
      build="916";;
    1.9.4)
      build="773";;
    1.8.8)
      build="443";;
    *)
      build="nosupp";;
  esac

  if [ $build != "nosupp" ]; then
    rm $SERVER
    downloadUrl=${PAPER_DOWNLOAD_URL:-https://papermc.io/ci/job/Paper/$build/artifact/paperclip.jar}
    curl -fsSL -o $SERVER "$downloadUrl"
    if [ ! -f $SERVER ]; then
      echo "ERROR: failed to download from $downloadUrl (status=$?)"
      exit 3
    fi
  else
    echo "ERROR: Version $VERSION is not supported for $TYPE"
    echo "       Refer to https://papermc.io/ci/job/Paper/"
    echo "       for supported versions"
    exit 2
  fi
fi

# Normalize on Spigot for operations below
export TYPE=SPIGOT

# Continue to Final Setup
exec start-finalSetup01World $@
